# Bun CLI fish completions (generated from completions/bun-cli.json)
# Source this file or place it in ~/.config/fish/completions/bun.fish

complete -c bun -f

complete -c bun -n '__fish_use_subcommand' -a 'run' -d 'Flags:'
complete -c bun -n '__fish_use_subcommand' -a 'test' -d 'Run all matching test files and print the results to stdout'
complete -c bun -n '__fish_use_subcommand' -a 'x' -d 'Execute an npm package executable (CLI), automatically installing into a global shared cache if not installed in node_modules.'
complete -c bun -n '__fish_use_subcommand' -a 'repl' -d 'Flags:'
complete -c bun -n '__fish_use_subcommand' -a 'exec' -d 'Execute a shell script directly from Bun.'
complete -c bun -n '__fish_use_subcommand' -a 'install' -d 'Install the dependencies listed in package.json.'
complete -c bun -n '__fish_use_subcommand' -a 'add' -d 'Add a new dependency to package.json and install it.'
complete -c bun -n '__fish_use_subcommand' -a 'remove' -d 'Remove a package from package.json and uninstall from node_modules.'
complete -c bun -n '__fish_use_subcommand' -a 'update' -d 'Update dependencies to their most recent versions within the version range in package.json.'
complete -c bun -n '__fish_use_subcommand' -a 'audit' -d 'Check installed packages for vulnerabilities.'
complete -c bun -n '__fish_use_subcommand' -a 'outdated' -d 'bun outdated v1.4.0-canary.1 (452139e36)'
complete -c bun -n '__fish_use_subcommand' -a 'link' -d 'Register a local directory as a "linkable" package, or link a "linkable" package to the current project.'
complete -c bun -n '__fish_use_subcommand' -a 'unlink' -d 'Unregister the current directory as a "linkable" package.'
complete -c bun -n '__fish_use_subcommand' -a 'publish' -d 'bun publish v1.4.0-canary.1 (452139e36)'
complete -c bun -n '__fish_use_subcommand' -a 'patch' -d 'Prepare a package for patching, or generate and save a patch.'
complete -c bun -n '__fish_use_subcommand' -a 'pm' -d 'Run package manager utilities.'
complete -c bun -n '__fish_use_subcommand' -a 'info' -d 'View package metadata from the registry.'
complete -c bun -n '__fish_use_subcommand' -a 'why' -d 'Explain why a package is installed'
complete -c bun -n '__fish_use_subcommand' -a 'build' -d 'Transpile and bundle one or more files.'
complete -c bun -n '__fish_use_subcommand' -a 'init' -d 'Initialize a Bun project in the current directory.'
complete -c bun -n '__fish_use_subcommand' -a 'create' -d 'bun create <MyReactComponent.(jsx|tsx)>'
complete -c bun -n '__fish_use_subcommand' -a 'upgrade' -d 'Upgrade Bun'
complete -c bun -n '__fish_use_subcommand' -a 'feedback' -d 'bun feedback'

complete -c bun -l silent -d 'Don'\''t print the script command'
complete -c bun -l elide-lines -r -d 'Number of lines of script output shown when using --filter (default: 10). Set to 0 to show all lines.'
complete -c bun -s v -l version -d 'Print version and exit'
complete -c bun -l revision -d 'Print version with revision and exit'
complete -c bun -s F -l filter -r -d 'Run a script in all workspace packages matching the pattern'
complete -c bun -s b -l bun -d 'Force a script or package to use Bun'\''s runtime instead of Node.js (via symlinking node)'
complete -c bun -l no-orphans -d 'Exit when the parent process dies, and on exit SIGKILL every descendant. Linux/macOS only.'
complete -c bun -l shell -r -d 'Control the shell used for package.json scripts. Supports either '\''bun'\'' or '\''system'\'''
complete -c bun -l workspaces -d 'Run a script in all workspace packages (from the "workspaces" field in package.json)'
complete -c bun -l parallel -d 'Run multiple scripts concurrently with Foreman-style output'
complete -c bun -l sequential -d 'Run multiple scripts sequentially with Foreman-style output'
complete -c bun -l no-exit-on-error -d 'Continue running other scripts when one fails (with --parallel/--sequential)'
complete -c bun -l watch -d 'Automatically restart the process on file change'
complete -c bun -l hot -d 'Enable auto reload in the Bun runtime, test runner, or bundler'
complete -c bun -l no-clear-screen -d 'Disable clearing the terminal screen on reload when --hot or --watch is enabled'
complete -c bun -l smol -d 'Use less memory, but run garbage collection more often'
complete -c bun -s r -l preload -r -d 'Import a module before other modules are loaded'
complete -c bun -l require -r -d 'Alias of --preload, for Node.js compatibility'
complete -c bun -l import -r -d 'Alias of --preload, for Node.js compatibility'
complete -c bun -l inspect -r -d 'Activate Bun'\''s debugger'
complete -c bun -l inspect-wait -r -d 'Activate Bun'\''s debugger, wait for a connection before executing'
complete -c bun -l inspect-brk -r -d 'Activate Bun'\''s debugger, set breakpoint on first line of code and wait'
complete -c bun -l cpu-prof -d 'Start CPU profiler and write profile to disk on exit'
complete -c bun -l cpu-prof-name -r -d 'Specify the name of the CPU profile file'
complete -c bun -l cpu-prof-dir -r -d 'Specify the directory where the CPU profile will be saved'
complete -c bun -l cpu-prof-md -d 'Output CPU profile in markdown format (grep-friendly, designed for LLM analysis)'
complete -c bun -l cpu-prof-interval -r -d 'Specify the sampling interval in microseconds for CPU profiling (default: 1000)'
complete -c bun -l heap-prof -d 'Generate V8 heap snapshot on exit (.heapsnapshot)'
complete -c bun -l heap-prof-name -r -d 'Specify the name of the heap profile file'
complete -c bun -l heap-prof-dir -r -d 'Specify the directory where the heap profile will be saved'
complete -c bun -l heap-prof-md -d 'Generate markdown heap profile on exit (for CLI analysis)'
complete -c bun -l if-present -d 'Exit without an error if the entrypoint does not exist'
complete -c bun -l no-install -d 'Disable auto install in the Bun runtime'
complete -c bun -l install -a 'auto' -d 'Configure auto-install behavior. One of "auto" (default, auto-installs when no node_modules), "fallback" (missing packages only), "force" (always).'
complete -c bun -s i -l i -d 'Auto-install dependencies during execution. Equivalent to --install=fallback.'
complete -c bun -s e -l eval -r -d 'Evaluate argument as a script'
complete -c bun -s p -l print -r -d 'Evaluate argument as a script and print the result'
complete -c bun -l prefer-offline -d 'Skip staleness checks for packages in the Bun runtime and resolve from disk'
complete -c bun -l prefer-latest -d 'Use the latest matching versions of packages in the Bun runtime, always checking npm'
complete -c bun -l port -r -d 'Set the default port for Bun.serve'
complete -c bun -l conditions -r -d 'Pass custom conditions to resolve'
complete -c bun -l fetch-preconnect -r -d 'Preconnect to a URL while code is loading'
complete -c bun -l experimental-http2-fetch -d 'Offer h2 in fetch() TLS ALPN. Same as BUN_FEATURE_FLAG_EXPERIMENTAL_HTTP2_CLIENT=1'
complete -c bun -l experimental-http3-fetch -d 'Honor Alt-Svc: h3 in fetch() and upgrade to HTTP/3. Same as BUN_FEATURE_FLAG_EXPERIMENTAL_HTTP3_CLIENT=1'
complete -c bun -l max-http-header-size -r -d 'Set the maximum size of HTTP headers in bytes. Default is 16KiB'
complete -c bun -l dns-result-order -a 'verbatim (default) ipv4first ipv6first' -d 'Set the default order of DNS lookup results. Valid orders: verbatim (default), ipv4first, ipv6first'
complete -c bun -l experimental-stream-iter -d 'Enable the experimental stream/iter API (node:stream/iter, node:zlib/iter).'
complete -c bun -l expose-gc -d 'Expose gc() on the global object. Has no effect on Bun.gc().'
complete -c bun -l no-deprecation -d 'Suppress all reporting of the custom deprecation.'
complete -c bun -l throw-deprecation -d 'Determine whether or not deprecation warnings result in errors.'
complete -c bun -l title -r -d 'Set the process title'
complete -c bun -l zero-fill-buffers -d 'Boolean to force Buffer.allocUnsafe(size) to be zero-filled.'
complete -c bun -l use-system-ca -d 'Use the system'\''s trusted certificate authorities'
complete -c bun -l use-openssl-ca -d 'Use OpenSSL'\''s default CA store'
complete -c bun -l use-bundled-ca -d 'Use bundled CA store'
complete -c bun -l redis-preconnect -d 'Preconnect to $REDIS_URL at startup'
complete -c bun -l sql-preconnect -d 'Preconnect to PostgreSQL at startup'
complete -c bun -l no-addons -d 'Throw an error if process.dlopen is called, and disable export condition "node-addons"'
complete -c bun -l unhandled-rejections -a 'strict' -d 'One of "strict", "throw", "warn", "none", or "warn-with-error-code"'
complete -c bun -l console-depth -r -d 'Set the default depth for console.log object inspection (default: 2)'
complete -c bun -l user-agent -r -d 'Set the default User-Agent header for HTTP requests'
complete -c bun -l cron-title -r -d 'Title for cron execution mode'
complete -c bun -l cron-period -r -d 'Cron period for cron execution mode'
complete -c bun -l main-fields -r -d 'Main fields to lookup in package.json. Defaults to --target dependent'
complete -c bun -l preserve-symlinks -d 'Preserve symlinks when resolving files'
complete -c bun -l preserve-symlinks-main -d 'Preserve symlinks when resolving the main entry point'
complete -c bun -l extension-order -r -d 'Defaults to: .tsx,.ts,.jsx,.js,.json'
complete -c bun -l tsconfig-override -r -d 'Specify custom tsconfig.json. Default $cwd/tsconfig.json'
complete -c bun -s d -l define -r -d 'Substitute K:V while parsing, e.g. --define process.env.NODE_ENV:"development". Values are parsed as JSON.'
complete -c bun -l drop -r -d 'Remove function calls, e.g. --drop=console removes all console.* calls.'
complete -c bun -l feature -r -d 'Enable a feature flag for dead-code elimination, e.g. --feature=SUPER_SECRET'
complete -c bun -s l -l loader -r -d 'Parse files with .ext:loader, e.g. --loader .js:jsx. Valid loaders: js, jsx, ts, tsx, json, toml, text, file, wasm, napi'
complete -c bun -l no-macros -d 'Disable macros from being executed in the bundler, transpiler and runtime'
complete -c bun -l jsx-factory -r -d 'Changes the function called when compiling JSX elements using the classic JSX runtime'
complete -c bun -l jsx-fragment -r -d 'Changes the function called when compiling JSX fragments'
complete -c bun -l jsx-import-source -r -d 'Declares the module specifier to be used for importing the jsx and jsxs factory functions. Default: "react"'
complete -c bun -l jsx-runtime -a 'automatic classic' -d '"automatic" (default) or "classic"'
complete -c bun -l jsx-side-effects -d 'Treat JSX elements as having side effects (disable pure annotations)'
complete -c bun -l ignore-dce-annotations -d 'Ignore tree-shaking annotations such as @__PURE__'
complete -c bun -l env-file -r -d 'Load environment variables from the specified file(s)'
complete -c bun -l no-env-file -d 'Disable automatic loading of .env files'
complete -c bun -l cwd -r -d 'Absolute path to resolve files & entry points from. This just changes the process'\'' cwd.'
complete -c bun -s c -l config -r -d 'Specify path to Bun config file. Default $cwd/bunfig.toml'
complete -c bun -s h -l help -d 'Display this menu and exit'

complete -c bun -n '__fish_seen_subcommand_from run' -a '(bun getcompletes files)' -d 'file'
complete -c bun -n '__fish_seen_subcommand_from run' -a '(bun getcompletes scripts)' -d 'Script'
complete -c bun -n '__fish_seen_subcommand_from run' -a '(bun getcompletes binaries)' -d 'Binary'
complete -c bun -n '__fish_seen_subcommand_from test' -l no-orphans -d 'Exit when the parent process dies, and on exit SIGKILL every descendant. Linux/macOS only.'
complete -c bun -n '__fish_seen_subcommand_from test' -l timeout -r -d 'Set the per-test timeout in milliseconds, default is 5000.'
complete -c bun -n '__fish_seen_subcommand_from test' -s u -l update-snapshots -d 'Update snapshot files'
complete -c bun -n '__fish_seen_subcommand_from test' -l rerun-each -r -d 'Re-run each test file  times, helps catch certain bugs'
complete -c bun -n '__fish_seen_subcommand_from test' -l retry -r -d 'Default retry count for all tests, overridden by per-test { retry: N }'
complete -c bun -n '__fish_seen_subcommand_from test' -l todo -d 'Include tests that are marked with "test.todo()"'
complete -c bun -n '__fish_seen_subcommand_from test' -l only -d 'Run only tests that are marked with "test.only()" or "describe.only()"'
complete -c bun -n '__fish_seen_subcommand_from test' -l pass-with-no-tests -d 'Exit with code 0 when no tests are found'
complete -c bun -n '__fish_seen_subcommand_from test' -l concurrent -d 'Treat all tests as `test.concurrent()` tests'
complete -c bun -n '__fish_seen_subcommand_from test' -l randomize -d 'Run tests in random order'
complete -c bun -n '__fish_seen_subcommand_from test' -l seed -r -d 'Set the random seed for test randomization'
complete -c bun -n '__fish_seen_subcommand_from test' -l coverage -d 'Generate a coverage profile'
complete -c bun -n '__fish_seen_subcommand_from test' -l coverage-reporter -r -d 'Report coverage in '\''text'\'' and/or '\''lcov'\''. Defaults to '\''text'\''.'
complete -c bun -n '__fish_seen_subcommand_from test' -l coverage-dir -r -d 'Directory for coverage files. Defaults to '\''coverage'\''.'
complete -c bun -n '__fish_seen_subcommand_from test' -l bail -r -d 'Exit the test suite after  failures. If you do not specify a number, it defaults to 1.'
complete -c bun -n '__fish_seen_subcommand_from test' -s t -l test-name-pattern -r -d 'Run only tests with a name that matches the given regex.'
complete -c bun -n '__fish_seen_subcommand_from test' -l reporter -r -d 'Test output reporter format. Available: '\''junit'\'' (requires --reporter-outfile), '\''dots'\''. Default: console output.'
complete -c bun -n '__fish_seen_subcommand_from test' -l reporter-outfile -r -d 'Output file path for the reporter format (required with --reporter).'
complete -c bun -n '__fish_seen_subcommand_from test' -l dots -d 'Enable dots reporter. Shorthand for --reporter=dots.'
complete -c bun -n '__fish_seen_subcommand_from test' -l only-failures -d 'Only display test failures, hiding passing tests.'
complete -c bun -n '__fish_seen_subcommand_from test' -l max-concurrency -r -d 'Maximum number of concurrent tests to execute at once. Default is 20.'
complete -c bun -n '__fish_seen_subcommand_from test' -l path-ignore-patterns -r -d 'Glob patterns for test file paths to ignore.'
complete -c bun -n '__fish_seen_subcommand_from test' -l changed -r -d 'Only run test files affected by changed files according to git. Optionally pass a commit or branch to compare against.'
complete -c bun -n '__fish_seen_subcommand_from test' -l isolate -d 'Run each test file in a fresh global object. Leaked handles from one file cannot affect another.'
complete -c bun -n '__fish_seen_subcommand_from test' -l parallel -r -d 'Run test files in parallel using N worker processes. Implies --isolate. Defaults to CPU core count.'
complete -c bun -n '__fish_seen_subcommand_from test' -l parallel-delay -r -d 'Milliseconds the first --parallel worker must be busy before spawning the rest. 0 spawns all immediately. Default 5.'
complete -c bun -n '__fish_seen_subcommand_from test' -l test-worker -d '(internal) Run as a --parallel worker, receiving files over IPC.'
complete -c bun -n '__fish_seen_subcommand_from test' -l shard -r -d 'Run a subset of test files, e.g. '\''--shard=1/3'\'' runs the first of three shards. Useful for splitting tests across multiple CI jobs.'
complete -c bun -n '__fish_seen_subcommand_from test' -a '(bun getcompletes files)' -d 'patterns'
complete -c bun -n '__fish_seen_subcommand_from x' -l bun -d 'Force the command to run with Bun instead of Node.js'
complete -c bun -n '__fish_seen_subcommand_from x' -s p -l package -d '<package>    Specify package to install when binary name differs from package name'
complete -c bun -n '__fish_seen_subcommand_from x' -l no-install -d 'Skip installation if package is not already installed'
complete -c bun -n '__fish_seen_subcommand_from x' -l verbose -d 'Enable verbose output during installation'
complete -c bun -n '__fish_seen_subcommand_from x' -l silent -d 'Suppress output during installation'
complete -c bun -n '__fish_seen_subcommand_from x' -a '(bun getcompletes packages)' -d 'package@version'
complete -c bun -n '__fish_seen_subcommand_from repl' -a '(bun getcompletes files)' -d 'file'
complete -c bun -n '__fish_seen_subcommand_from exec' -a '(bun getcompletes scripts)' -d 'script'
complete -c bun -n '__fish_seen_subcommand_from install' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from install' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from install' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from install' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from install' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from install' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from install' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from install' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from install' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from install' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from install' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from install' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from install' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from install' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from install' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from install' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from install' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from install' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from install' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from install' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from install' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from install' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from install' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from install' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from install' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from install' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from install' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from install' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from install' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from install' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from install' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from install' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from install' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from install' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from install' -s d -l dev -d 'Add dependency to "devDependencies"'
complete -c bun -n '__fish_seen_subcommand_from install' -l optional -d 'Add dependency to "optionalDependencies"'
complete -c bun -n '__fish_seen_subcommand_from install' -l peer -d 'Add dependency to "peerDependencies"'
complete -c bun -n '__fish_seen_subcommand_from install' -s E -l exact -d 'Add the exact version instead of the ^range'
complete -c bun -n '__fish_seen_subcommand_from install' -s F -l filter -r -d 'Install packages for the matching workspaces'
complete -c bun -n '__fish_seen_subcommand_from install' -s a -l analyze -d 'Analyze & install all dependencies of files passed as arguments recursively (using Bun'\''s bundler)'
complete -c bun -n '__fish_seen_subcommand_from install' -l only-missing -d 'Only add dependencies to package.json if they are not already present'
complete -c bun -n '__fish_seen_subcommand_from install' -a '(bun getcompletes packages)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from add' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from add' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from add' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from add' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from add' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from add' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from add' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from add' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from add' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from add' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from add' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from add' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from add' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from add' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from add' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from add' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from add' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from add' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from add' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from add' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from add' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from add' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from add' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from add' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from add' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from add' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from add' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from add' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from add' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from add' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from add' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from add' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from add' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from add' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from add' -s d -l dev -d 'Add dependency to "devDependencies"'
complete -c bun -n '__fish_seen_subcommand_from add' -l optional -d 'Add dependency to "optionalDependencies"'
complete -c bun -n '__fish_seen_subcommand_from add' -l peer -d 'Add dependency to "peerDependencies"'
complete -c bun -n '__fish_seen_subcommand_from add' -s E -l exact -d 'Add the exact version instead of the ^range'
complete -c bun -n '__fish_seen_subcommand_from add' -s a -l analyze -d 'Recursively analyze & install dependencies of files passed as arguments (using Bun'\''s bundler)'
complete -c bun -n '__fish_seen_subcommand_from add' -l only-missing -d 'Only add dependencies to package.json if they are not already present'
complete -c bun -n '__fish_seen_subcommand_from add' -a '(bun getcompletes packages)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from remove' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from remove' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from remove' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from remove' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from remove' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from remove' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from remove' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from remove' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from remove' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from remove' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from remove' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from remove' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from remove' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from remove' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from remove' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from remove' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from remove' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from remove' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from remove' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from remove' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from remove' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from remove' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from remove' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from remove' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from remove' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from remove' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from remove' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from remove' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from remove' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from remove' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from remove' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from remove' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from remove' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from remove' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from remove' -a '(bun getcompletes packages)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from update' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from update' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from update' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from update' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from update' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from update' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from update' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from update' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from update' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from update' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from update' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from update' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from update' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from update' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from update' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from update' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from update' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from update' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from update' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from update' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from update' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from update' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from update' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from update' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from update' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from update' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from update' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from update' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from update' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from update' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from update' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from update' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from update' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from update' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from update' -l latest -d 'Update packages to their latest versions'
complete -c bun -n '__fish_seen_subcommand_from update' -s i -l interactive -d 'Show an interactive list of outdated packages to select for update'
complete -c bun -n '__fish_seen_subcommand_from update' -l filter -r -d 'Update packages for the matching workspaces'
complete -c bun -n '__fish_seen_subcommand_from update' -s r -l recursive -d 'Update packages in all workspaces'
complete -c bun -n '__fish_seen_subcommand_from update' -a '(bun getcompletes packages)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from audit' -l json -d 'Output in JSON format'
complete -c bun -n '__fish_seen_subcommand_from audit' -l audit-level -r -d 'Only print advisories with severity greater than or equal to  (low, moderate, high, critical)'
complete -c bun -n '__fish_seen_subcommand_from audit' -l ignore -r -d 'Ignore specific CVE IDs from audit'
complete -c bun -n '__fish_seen_subcommand_from audit' -s p -l production -d 'Audit only production dependencies (excludes devDependencies)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s F -l filter -r -d 'Display outdated dependencies for each matching workspace'
complete -c bun -n '__fish_seen_subcommand_from outdated' -s r -l recursive -d 'Check outdated packages in all workspaces'
complete -c bun -n '__fish_seen_subcommand_from outdated' -a '(bun getcompletes packages)' -d 'filter'
complete -c bun -n '__fish_seen_subcommand_from link' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from link' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from link' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from link' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from link' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from link' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from link' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from link' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from link' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from link' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from link' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from link' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from link' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from link' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from link' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from link' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from link' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from link' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from link' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from link' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from link' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from link' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from link' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from link' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from link' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from link' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from link' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from link' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from link' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from link' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from link' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from link' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from link' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from link' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from link' -a '(__fish_complete_path)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from unlink' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from unlink' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from unlink' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from unlink' -a '(bun getcompletes packages)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from publish' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from publish' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from publish' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from publish' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from publish' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from publish' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from publish' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from publish' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from publish' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from publish' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from publish' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from publish' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from publish' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from publish' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from publish' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from publish' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from publish' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from publish' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from publish' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from publish' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from publish' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from publish' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from publish' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from publish' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from publish' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from publish' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from publish' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from publish' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from publish' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from publish' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from publish' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from publish' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from publish' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from publish' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from publish' -l access -r -d 'Set access level for scoped packages'
complete -c bun -n '__fish_seen_subcommand_from publish' -l tag -r -d 'Tag the release. Default is "latest"'
complete -c bun -n '__fish_seen_subcommand_from publish' -l otp -r -d 'Provide a one-time password for authentication'
complete -c bun -n '__fish_seen_subcommand_from publish' -l auth-type -r -d 'Specify the type of one-time password authentication (default is '\''web'\'')'
complete -c bun -n '__fish_seen_subcommand_from publish' -l gzip-level -r -d 'Specify a custom compression level for gzip. Default is 9.'
complete -c bun -n '__fish_seen_subcommand_from publish' -l tolerate-republish -d 'Don'\''t exit with code 1 when republishing over an existing version number'
complete -c bun -n '__fish_seen_subcommand_from publish' -a '(bun getcompletes files)' -d 'dist'
complete -c bun -n '__fish_seen_subcommand_from patch' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from patch' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from patch' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from patch' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from patch' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from patch' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from patch' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from patch' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from patch' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from patch' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from patch' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from patch' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from patch' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from patch' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from patch' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from patch' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from patch' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from patch' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from patch' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from patch' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from patch' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from patch' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from patch' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from patch' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from patch' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from patch' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from patch' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from patch' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from patch' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from patch' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from patch' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from patch' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from patch' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from patch' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from patch' -l commit -d 'Install a package containing modifications in `dir`'
complete -c bun -n '__fish_seen_subcommand_from patch' -l patches-dir -r -d 'The directory to put the patch file in (only if --commit is used)'
complete -c bun -n '__fish_seen_subcommand_from patch' -a '(bun getcompletes packages)' -d 'flags'
complete -c bun -n '__fish_seen_subcommand_from info' -s c -l config -r -d 'Specify path to config file (bunfig.toml)'
complete -c bun -n '__fish_seen_subcommand_from info' -s y -l yarn -d 'Write a yarn.lock file (yarn v1)'
complete -c bun -n '__fish_seen_subcommand_from info' -s p -l production -d 'Don'\''t install devDependencies'
complete -c bun -n '__fish_seen_subcommand_from info' -l no-save -d 'Don'\''t update package.json or save a lockfile'
complete -c bun -n '__fish_seen_subcommand_from info' -l save -d 'Save to package.json (true by default)'
complete -c bun -n '__fish_seen_subcommand_from info' -l ca -r -d 'Provide a Certificate Authority signing certificate'
complete -c bun -n '__fish_seen_subcommand_from info' -l cafile -r -d 'The same as `--ca`, but is a file path to the certificate'
complete -c bun -n '__fish_seen_subcommand_from info' -l dry-run -d 'Perform a dry run without making changes'
complete -c bun -n '__fish_seen_subcommand_from info' -l frozen-lockfile -d 'Disallow changes to lockfile'
complete -c bun -n '__fish_seen_subcommand_from info' -s f -l force -d 'Always request the latest versions from the registry & reinstall all dependencies'
complete -c bun -n '__fish_seen_subcommand_from info' -l cache-dir -r -d 'Store & load cached data from a specific directory path'
complete -c bun -n '__fish_seen_subcommand_from info' -l no-cache -d 'Ignore manifest cache entirely'
complete -c bun -n '__fish_seen_subcommand_from info' -l silent -d 'Don'\''t log anything'
complete -c bun -n '__fish_seen_subcommand_from info' -l quiet -d 'Only show tarball name when packing'
complete -c bun -n '__fish_seen_subcommand_from info' -l verbose -d 'Excessively verbose logging'
complete -c bun -n '__fish_seen_subcommand_from info' -l no-progress -d 'Disable the progress bar'
complete -c bun -n '__fish_seen_subcommand_from info' -l no-summary -d 'Don'\''t print a summary'
complete -c bun -n '__fish_seen_subcommand_from info' -l no-verify -d 'Skip verifying integrity of newly downloaded packages'
complete -c bun -n '__fish_seen_subcommand_from info' -l ignore-scripts -d 'Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)'
complete -c bun -n '__fish_seen_subcommand_from info' -l trust -d 'Add to trustedDependencies in the project'\''s package.json and install the package(s)'
complete -c bun -n '__fish_seen_subcommand_from info' -s g -l global -d 'Install globally'
complete -c bun -n '__fish_seen_subcommand_from info' -l cwd -r -d 'Set a specific cwd'
complete -c bun -n '__fish_seen_subcommand_from info' -l backend -a 'clonefile hardlink symlink copyfile' -d 'Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"'
complete -c bun -n '__fish_seen_subcommand_from info' -l registry -r -d 'Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables'
complete -c bun -n '__fish_seen_subcommand_from info' -l concurrent-scripts -r -d 'Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)'
complete -c bun -n '__fish_seen_subcommand_from info' -l network-concurrency -r -d 'Maximum number of concurrent network requests (default 48)'
complete -c bun -n '__fish_seen_subcommand_from info' -l save-text-lockfile -d 'Save a text-based lockfile'
complete -c bun -n '__fish_seen_subcommand_from info' -l omit -a 'dev optional peer' -d 'Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install'
complete -c bun -n '__fish_seen_subcommand_from info' -l lockfile-only -d 'Generate a lockfile without installing dependencies'
complete -c bun -n '__fish_seen_subcommand_from info' -l linker -a 'isolated hoisted' -d 'Linker strategy (one of "isolated" or "hoisted")'
complete -c bun -n '__fish_seen_subcommand_from info' -l minimum-release-age -r -d 'Only install packages published at least N seconds ago (security feature)'
complete -c bun -n '__fish_seen_subcommand_from info' -l cpu -a 'arm64 x64 ia32 ppc64 s390x' -d 'Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)'
complete -c bun -n '__fish_seen_subcommand_from info' -l os -a 'linux darwin win32 freebsd openbsd sunos aix' -d 'Override operating system for optional dependencies (e.g., linux, darwin, * for all)'
complete -c bun -n '__fish_seen_subcommand_from info' -s h -l help -d 'Print this help menu'
complete -c bun -n '__fish_seen_subcommand_from info' -l json -d 'Output in JSON format'
complete -c bun -n '__fish_seen_subcommand_from info' -a '(bun getcompletes packages)' -d '@'
complete -c bun -n '__fish_seen_subcommand_from why' -l top -d 'Show only the top dependency tree instead of nested ones'
complete -c bun -n '__fish_seen_subcommand_from why' -l depth -d '<NUM> Maximum depth of the dependency tree to display'
complete -c bun -n '__fish_seen_subcommand_from why' -a '(bun getcompletes packages)' -d 'package@version'
complete -c bun -n '__fish_seen_subcommand_from build' -l production -d 'Set NODE_ENV=production and enable minification'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile -d 'Generate a standalone Bun executable containing your bundled code. Implies --production'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile-exec-argv -r -d 'Prepend arguments to the standalone executable'\''s execArgv'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile-autoload-dotenv -d 'Enable autoloading of .env files in standalone executable (default: true)'
complete -c bun -n '__fish_seen_subcommand_from build' -l no-compile-autoload-dotenv -d 'Disable autoloading of .env files in standalone executable'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile-autoload-bunfig -d 'Enable autoloading of bunfig.toml in standalone executable (default: true)'
complete -c bun -n '__fish_seen_subcommand_from build' -l no-compile-autoload-bunfig -d 'Disable autoloading of bunfig.toml in standalone executable'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile-autoload-tsconfig -d 'Enable autoloading of tsconfig.json at runtime in standalone executable (default: false)'
complete -c bun -n '__fish_seen_subcommand_from build' -l no-compile-autoload-tsconfig -d 'Disable autoloading of tsconfig.json at runtime in standalone executable'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile-autoload-package-json -d 'Enable autoloading of package.json at runtime in standalone executable (default: false)'
complete -c bun -n '__fish_seen_subcommand_from build' -l no-compile-autoload-package-json -d 'Disable autoloading of package.json at runtime in standalone executable'
complete -c bun -n '__fish_seen_subcommand_from build' -l compile-executable-path -r -d 'Path to a Bun executable to use for cross-compilation instead of downloading'
complete -c bun -n '__fish_seen_subcommand_from build' -l bytecode -d 'Use a bytecode cache'
complete -c bun -n '__fish_seen_subcommand_from build' -l watch -d 'Automatically restart the process on file change'
complete -c bun -n '__fish_seen_subcommand_from build' -l no-clear-screen -d 'Disable clearing the terminal screen on reload when --watch is enabled'
complete -c bun -n '__fish_seen_subcommand_from build' -l target -a 'browser bun node' -d 'The intended execution environment for the bundle. "browser", "bun" or "node"'
complete -c bun -n '__fish_seen_subcommand_from build' -l outdir -r -d 'Default to "dist" if multiple files'
complete -c bun -n '__fish_seen_subcommand_from build' -l outfile -r -d 'Write to a file'
complete -c bun -n '__fish_seen_subcommand_from build' -l metafile -r -d 'Write a JSON file with metadata about the build'
complete -c bun -n '__fish_seen_subcommand_from build' -l metafile-md -r -d 'Write a markdown file with a visualization of the module graph (LLM-friendly)'
complete -c bun -n '__fish_seen_subcommand_from build' -l sourcemap -r -d 'Build with sourcemaps - '\''linked'\'', '\''inline'\'', '\''external'\'', or '\''none'\'''
complete -c bun -n '__fish_seen_subcommand_from build' -l banner -r -d 'Add a banner to the bundled output such as "use client"; for a bundle being used with RSCs'
complete -c bun -n '__fish_seen_subcommand_from build' -l footer -r -d 'Add a footer to the bundled output such as // built with bun!'
complete -c bun -n '__fish_seen_subcommand_from build' -l format -a 'esm cjs iife esm cjs' -d 'Specifies the module format to build to. "esm", "cjs" and "iife" are supported. Defaults to "esm", or "cjs" with --bytecode.'
complete -c bun -n '__fish_seen_subcommand_from build' -l root -r -d 'Root directory used for multiple entry points'
complete -c bun -n '__fish_seen_subcommand_from build' -l splitting -d 'Enable code splitting'
complete -c bun -n '__fish_seen_subcommand_from build' -l public-path -r -d 'A prefix to be appended to any import paths in bundled code'
complete -c bun -n '__fish_seen_subcommand_from build' -s e -l external -r -d 'Exclude module from transpilation (can use * wildcards). ex: -e react'
complete -c bun -n '__fish_seen_subcommand_from build' -l allow-unresolved -r -d 'Allow unresolved dynamic import()/require() specifiers matching these glob patterns. Use '\'''\'' for opaque specifiers. Default is '\''*'\'' (allow all).'
complete -c bun -n '__fish_seen_subcommand_from build' -l reject-unresolved -d 'Fail the build on any dynamic import()/require() specifier that cannot be resolved at build time.'
complete -c bun -n '__fish_seen_subcommand_from build' -l packages -a 'external bundle bundle' -d 'Add dependencies to bundle or keep them external. "external", "bundle" is supported. Defaults to "bundle".'
complete -c bun -n '__fish_seen_subcommand_from build' -l entry-naming -r -d 'Customize entry point filenames. Defaults to "[dir]/[name].[ext]"'
complete -c bun -n '__fish_seen_subcommand_from build' -l chunk-naming -r -d 'Customize chunk filenames. Defaults to "[name]-[hash].[ext]"'
complete -c bun -n '__fish_seen_subcommand_from build' -l asset-naming -r -d 'Customize asset filenames. Defaults to "[name]-[hash].[ext]"'
complete -c bun -n '__fish_seen_subcommand_from build' -l react-fast-refresh -d 'Enable React Fast Refresh transform (does not emit hot-module code, use this for testing)'
complete -c bun -n '__fish_seen_subcommand_from build' -l react-compiler -d 'Enable the React Compiler optimizing transform'
complete -c bun -n '__fish_seen_subcommand_from build' -l no-bundle -d 'Transpile file only, do not bundle'
complete -c bun -n '__fish_seen_subcommand_from build' -l emit-dce-annotations -d 'Re-emit DCE annotations in bundles. Enabled by default unless --minify-whitespace is passed.'
complete -c bun -n '__fish_seen_subcommand_from build' -l minify -d 'Enable all minification flags'
complete -c bun -n '__fish_seen_subcommand_from build' -l minify-syntax -d 'Minify syntax and inline data'
complete -c bun -n '__fish_seen_subcommand_from build' -l minify-whitespace -d 'Minify whitespace'
complete -c bun -n '__fish_seen_subcommand_from build' -l minify-identifiers -d 'Minify identifiers'
complete -c bun -n '__fish_seen_subcommand_from build' -l keep-names -d 'Preserve original function and class names when minifying'
complete -c bun -n '__fish_seen_subcommand_from build' -l css-chunking -d 'Chunk CSS files together to reduce duplicated CSS loaded in a browser. Only has an effect when multiple entrypoints import CSS'
complete -c bun -n '__fish_seen_subcommand_from build' -l conditions -r -d 'Pass custom conditions to resolve'
complete -c bun -n '__fish_seen_subcommand_from build' -l app -d '(EXPERIMENTAL) Build a web app for production using Bun Bake.'
complete -c bun -n '__fish_seen_subcommand_from build' -l server-components -d '(EXPERIMENTAL) Enable server components'
complete -c bun -n '__fish_seen_subcommand_from build' -l env -r -d 'Inline environment variables into the bundle as process.env.${name}. Defaults to '\''disable'\''. To inline environment variables matching a prefix, use my prefix like '\''FOO_PUBLIC_*'\''.'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-hide-console -d 'When using --compile targeting Windows, prevent a Command prompt from opening alongside the executable'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-icon -r -d 'When using --compile targeting Windows, assign an executable icon'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-title -r -d 'When using --compile targeting Windows, set the executable product name'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-publisher -r -d 'When using --compile targeting Windows, set the executable company name'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-version -r -d 'When using --compile targeting Windows, set the executable version (e.g. 1.2.3.4)'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-description -r -d 'When using --compile targeting Windows, set the executable description'
complete -c bun -n '__fish_seen_subcommand_from build' -l windows-copyright -r -d 'When using --compile targeting Windows, set the executable copyright'
complete -c bun -n '__fish_seen_subcommand_from build' -l debug-dump-server-files -d 'When --app is set, dump all server files to disk even when building statically'
complete -c bun -n '__fish_seen_subcommand_from build' -l debug-no-minify -d 'When --app is set, do not minify anything'
complete -c bun -n '__fish_seen_subcommand_from build' -a '(bun getcompletes files)' -d 'File'
complete -c bun -n '__fish_seen_subcommand_from init' -l help -d 'Print this menu'
complete -c bun -n '__fish_seen_subcommand_from init' -s y -l yes -d 'Accept all default options'
complete -c bun -n '__fish_seen_subcommand_from init' -s m -l minimal -d 'Only initialize type definitions'
complete -c bun -n '__fish_seen_subcommand_from init' -s r -l react -d 'Initialize a React project'
complete -c bun -n '__fish_seen_subcommand_from init' -l react -r -d 'Initialize a React project with TailwindCSS'
complete -c bun -n '__fish_seen_subcommand_from init' -l react -r -d 'Initialize a React project with @shadcn/ui and TailwindCSS'
complete -c bun -n '__fish_seen_subcommand_from init' -l cwd -r -d 'Run bun init as if started in a different working directory'
complete -c bun -n '__fish_seen_subcommand_from init' -a '(__fish_complete_directories)' -d 'folder'
complete -c bun -n '__fish_seen_subcommand_from create' -l force -d 'Overwrite existing files'
complete -c bun -n '__fish_seen_subcommand_from create' -l no-install -d 'Skip installing node_modules & tasks'
complete -c bun -n '__fish_seen_subcommand_from create' -l no-git -d 'Don'\''t initialize a git repository'
complete -c bun -n '__fish_seen_subcommand_from create' -l open -d 'Start & open in-browser after finish'
complete -c bun -n '__fish_seen_subcommand_from upgrade' -l canary -d 'Upgrade to the latest canary build'
complete -c bun -n '__fish_seen_subcommand_from upgrade' -l stable -d 'Switch from canary back to the latest stable release'
