#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";
/**
 * api-docs — scaffold Bun native API docs and tests from official docs.
 *
 * Usage:
 *   bun run api-docs --url https://bun.com/docs/api/http --name "HTTP Server"
 *
 * The script fetches the page, extracts the title and code blocks, and
 * creates:
 *   - a new section in `docs/ARCHITECTURE.md`
 *   - a test file under `test/bun-api/` that runs each code example
 *
 * The generated tests are smoke tests: each code block is executed with
 * `bun -e` and the test asserts a zero exit code. The README test count is
 * updated by running `bun run update-readme-test-counts`.
 */
import { mkdir } from "node:fs/promises";

interface Args {
	url: string;
	name: string;
}

function parseArgs(): Args {
	let url: string | undefined;
	let name: string | undefined;

	for (let i = 0; i < Bun.argv.length; i++) {
		if (Bun.argv[i] === "--url" && Bun.argv[i + 1]) {
			url = Bun.argv[i + 1];
			i++;
		} else if (Bun.argv[i] === "--name" && Bun.argv[i + 1]) {
			name = Bun.argv[i + 1];
			i++;
		}
	}

	if (!url || !name) {
		console.error("Usage: bun run api-docs --url <url> --name <name>");
		process.exit(1);
	}

	return { url, name };
}

function slugify(name: string): string {
	return name
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "");
}

function extractTitle(markdown: string, fallback: string): string {
	const match = markdown.match(/^#\s+(.+)$/m);
	return match?.[1].trim() ?? fallback;
}

function extractCodeBlocks(markdown: string): string[] {
	const blocks: string[] = [];
	const regex = /```(?:typescript|ts|javascript|js)?\n([\s\S]*?)```/g;
	let match: RegExpExecArray | null = regex.exec(markdown);
	while (match !== null) {
		const code = match[1].trim();
		if (code) blocks.push(code);
		match = regex.exec(markdown);
	}
	return blocks;
}

function generateTestFile(name: string, codeBlocks: string[]): string {
	const slug = slugify(name);
	const tests = codeBlocks
		.map((code, index) => {
			const escaped = code.replace(/`/g, "\\`").replace(/\$/g, "\\$");
			return `
test("${slug} example ${index + 1} runs without error", async () => {
	const code = \`${escaped}\`;
	const proc = Bun.spawn(["bun", "-e", code], {
		stdout: "ignore",
		stderr: "pipe",
	});
	const exitCode = await proc.exited;
	expect(exitCode).toBe(0);
});`;
		})
		.join("\n");

	return `import { test, expect } from "bun:test";

// Generated by api-docs from "${name}"
${tests}
`;
}

function generateArchSection(
	name: string,
	url: string,
	markdown: string,
	codeBlocks: string[],
): string {
	const title = extractTitle(markdown, name);
	const rows = codeBlocks
		.map((code, index) => {
			const firstLine = code.split("\n")[0] ?? "";
			return `| Example ${index + 1} | \`${firstLine.slice(0, 60)}\` |`;
		})
		.join("\n");

	return `

### ${title}

Source: <${url}>

| Example | First line |
| ------- | ---------- |
${rows}

\`\`\`typescript
${codeBlocks[0] ?? "// No code examples found"}
\`\`\`
`;
}

async function main(): Promise<number> {
	const { url, name } = parseArgs();
	console.log(`Fetching ${url}...`);

	const response = await fetch(url);
	if (!response.ok) {
		console.error(`Failed to fetch ${url}: ${response.status}`);
		return 1;
	}
	const markdown = await response.text();
	const codeBlocks = extractCodeBlocks(markdown);
	console.log(`Found ${codeBlocks.length} code blocks.`);

	if (codeBlocks.length === 0) {
		console.log("No code examples found; nothing to generate.");
		return 0;
	}

	const slug = slugify(name);
	const testDir = "test/bun-api";
	await mkdir(testDir, { recursive: true });
	const testPath = `${testDir}/${slug}.test.ts`;
	writeFileSync(testPath, generateTestFile(name, codeBlocks));
	console.log(`Wrote ${testPath}`);

	const archPath = "docs/ARCHITECTURE.md";
	let arch = readFileSync(archPath, "utf8");
	arch += generateArchSection(name, url, markdown, codeBlocks);
	writeFileSync(archPath, arch);
	console.log(`Updated ${archPath}`);

	console.log("Updating README test counts...");
	const result = Bun.spawnSync({
		cmd: ["bun", "run", "update-readme-test-counts"],
		stdout: "inherit",
		stderr: "inherit",
	});
	if (result.exitCode !== 0) {
		console.error("Failed to update README test counts.");
		return result.exitCode ?? 1;
	}

	console.log("Done.");
	return 0;
}

process.exit(await main());
