import { expect, test } from "bun:test";

// Generated by api-docs from bun-types "Bun File"

test("bun-file example 1 transpiles without error", () => {
	const code = `foo.size; // number of bytes
foo.type; // MIME type`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 2 transpiles without error", () => {
	const code = `await foo.text(); // contents as a string
await foo.json(); // contents as a JSON object
await foo.stream(); // contents as ReadableStream
await foo.arrayBuffer(); // contents as ArrayBuffer
await foo.bytes(); // contents as Uint8Array`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 3 transpiles without error", () => {
	const code = `Bun.file(new URL(import.meta.url)); // reference to the current file`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 4 transpiles without error", () => {
	const code = `notreal.size; // 0
notreal.type; // "text/plain;charset=utf-8"
const exists = await notreal.exists(); // false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 5 transpiles without error", () => {
	const code = `notreal.type; // => "application/json;charset=utf-8"`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 6 transpiles without error", () => {
	const code = `Bun.stdout;
Bun.stderr;`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 7 transpiles without error", () => {
	const code = `await Bun.write("output.txt", data);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 8 transpiles without error", () => {
	const code = `const output = Bun.file("output.txt"); // doesn't exist yet!
await Bun.write(output, input);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 9 transpiles without error", () => {
	const code = `const data = encoder.encode("datadatadata"); // Uint8Array
await Bun.write("output.txt", data);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 10 transpiles without error", () => {
	const code = `await Bun.write(Bun.stdout, input);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 11 transpiles without error", () => {
	const code = `await Bun.write("index.html", response);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 12 transpiles without error", () => {
	const code = `const writer = file.writer();`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 13 transpiles without error", () => {
	const code = `const writer = file.writer();

writer.write("it was the best of times\\n");
writer.write("it was the worst of times\\n");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 14 transpiles without error", () => {
	const code = `const writer = file.writer({ highWaterMark: 1024 * 1024 }); // 1MB`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 15 transpiles without error", () => {
	const code = `// to "re-ref" it later
writer.ref();`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 16 transpiles without error", () => {
	const code = `// read all the files in the current directory
const files = await readdir(import.meta.dir);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 17 transpiles without error", () => {
	const code = `// read all the files in the current directory, recursively
const files = await readdir("../", { recursive: true });`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 18 transpiles without error", () => {
	const code = `await mkdir("path/to/dir", { recursive: true });`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("bun-file example 19 transpiles without error", () => {
	const code = `// Usage
// bun ./cat.ts ./path-to-file

import { resolve } from "path";

const path = resolve(process.argv.at(-1));
await Bun.write(Bun.stdout, Bun.file(path));`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
