import { expect, test } from "bun:test";

// Generated by api-docs from bun-types "DNS"

test("dns example 1 transpiles without error", () => {
	const code = `const addrs = await dns.promises.resolve4("bun.com", { ttl: true });
console.log(addrs);
// => [{ address: "172.67.161.226", family: 4, ttl: 0 }, ...]`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("dns example 2 transpiles without error", () => {
	const code = `dns.prefetch("bun.com", 443);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("dns example 3 transpiles without error", () => {
	const code = `dns.prefetch("my.database-host.com", 5432);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("dns example 4 transpiles without error", () => {
	const code = `dns.prefetch("bun.com", 443);
//
// ... sometime later ...
await fetch("https://bun.com");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("dns example 5 transpiles without error", () => {
	const code = `const stats = dns.getCacheStats();
console.log(stats);
// => { cacheHitsCompleted: 0, cacheHitsInflight: 0, cacheMisses: 0, size: 0, errors: 0, totalCount: 0 }`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
