import { expect, test } from "bun:test";

// Generated by api-docs from "Glob"

test("glob example 1 transpiles without error", () => {
	const code = `import { Glob } from "bun";

const glob = new Glob("**/*.ts");

// Scans the current working directory and each of its sub-directories recursively
for await (const file of glob.scan(".")) {
  console.log(file); // => "index.ts"
}`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 2 transpiles without error", () => {
	const code = `import { Glob } from "bun";

const glob = new Glob("*.ts");

glob.match("index.ts"); // => true
glob.match("index.js"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 3 transpiles without error", () => {
	const code = `class Glob {
  scan(root: string | ScanOptions): AsyncIterable<string>;
  scanSync(root: string | ScanOptions): Iterable<string>;

  match(path: string): boolean;
}

interface ScanOptions {
  /**
   * The root directory to start matching from. Defaults to \`process.cwd()\`
   */
  cwd?: string;

  /**
   * Allow patterns to match entries that begin with a period (\`.\`).
   *
   * @default false
   */
  dot?: boolean;

  /**
   * Return the absolute path for entries.
   *
   * @default false
   */
  absolute?: boolean;

  /**
   * Indicates whether to traverse descendants of symbolic link directories.
   *
   * @default false
   */
  followSymlinks?: boolean;

  /**
   * Throw an error when symbolic link is broken
   *
   * @default false
   */
  throwErrorOnBrokenSymlink?: boolean;

  /**
   * Return only files.
   *
   * @default true
   */
  onlyFiles?: boolean;
}`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 4 transpiles without error", () => {
	const code = `const glob = new Glob("???.ts");
glob.match("foo.ts"); // => true
glob.match("foobar.ts"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 5 transpiles without error", () => {
	const code = `const glob = new Glob("*.ts");
glob.match("index.ts"); // => true
glob.match("src/index.ts"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 6 transpiles without error", () => {
	const code = `const glob = new Glob("**/*.ts");
glob.match("index.ts"); // => true
glob.match("src/index.ts"); // => true
glob.match("src/index.js"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 7 transpiles without error", () => {
	const code = `const glob = new Glob("ba[rz].ts");
glob.match("bar.ts"); // => true
glob.match("baz.ts"); // => true
glob.match("bat.ts"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 8 transpiles without error", () => {
	const code = `const glob = new Glob("ba[a-z][0-9][^4-9].ts");
glob.match("bar01.ts"); // => true
glob.match("baz83.ts"); // => true
glob.match("bat22.ts"); // => true
glob.match("bat24.ts"); // => false
glob.match("ba0a8.ts"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 9 transpiles without error", () => {
	const code = `const glob = new Glob("{a,b,c}.ts");
glob.match("a.ts"); // => true
glob.match("b.ts"); // => true
glob.match("c.ts"); // => true
glob.match("d.ts"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 10 transpiles without error", () => {
	const code = `const glob = new Glob("!index.ts");
glob.match("index.ts"); // => false
glob.match("foo.ts"); // => true`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 11 transpiles without error", () => {
	const code = `const glob = new Glob("\\\\!index.ts");
glob.match("!index.ts"); // => true
glob.match("index.ts"); // => false`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("glob example 12 transpiles without error", () => {
	const code = `import { glob, globSync, promises } from "node:fs";

// Array of patterns
const files = await promises.glob(["**/*.ts", "**/*.js"]);

// Exclude patterns
const filtered = await promises.glob("**/*", {
  exclude: ["node_modules/**", "*.test.*"],
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
