import { expect, test } from "bun:test";

// Generated by api-docs from bun-types "Spawn"

test("spawn example 1 transpiles without error", () => {
	const code = `console.log(await proc.exited); // 0`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 2 transpiles without error", () => {
	const code = `const text = await proc.stdout.text();
console.log(text); // => "1.3.3\\n"`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 3 transpiles without error", () => {
	const code = `const proc = Bun.spawn(["bun", "--version"], {
  onExit(proc, exitCode, signalCode, error) {
    // exit handler
  },
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 4 transpiles without error", () => {
	const code = `const proc = Bun.spawn(["bun", "--version"]);

await proc.exited; // resolves when process exit
proc.killed; // boolean — was the process killed?
proc.exitCode; // null | number
proc.signalCode; // null | "SIGABRT" | "SIGALRM" | ...`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 5 transpiles without error", () => {
	const code = `const proc = Bun.spawn(["bun", "--version"]);
proc.kill();
proc.killed; // true

proc.kill(15); // specify a signal code
proc.kill("SIGTERM"); // specify a signal name`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 6 transpiles without error", () => {
	const code = `const proc = Bun.spawn(["bun", "--version"]);
proc.unref();`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 7 transpiles without error", () => {
	const code = `const proc = Bun.spawn(["bun", "--version"]);
await proc.exited;

const usage = proc.resourceUsage();
console.log(\`Max memory used: \${usage.maxRSS} bytes\`);
console.log(\`CPU time (user): \${usage.cpuTime.user} µs\`);
console.log(\`CPU time (system): \${usage.cpuTime.system} µs\`);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 8 transpiles without error", () => {
	const code = `const controller = new AbortController();
const { signal } = controller;

const proc = Bun.spawn({
  cmd: ["sleep", "100"],
  signal,
});

// Later, to abort the process:
controller.abort();`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 9 transpiles without error", () => {
	const code = `// Kill the process after 5 seconds
const proc = Bun.spawn({
  cmd: ["sleep", "10"],
  timeout: 5000, // 5 seconds in milliseconds
});

await proc.exited; // Will resolve after 5 seconds`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 10 transpiles without error", () => {
	const code = `// Kill the process with SIGKILL after 5 seconds
const proc = Bun.spawn({
  cmd: ["sleep", "10"],
  timeout: 5000,
  killSignal: "SIGKILL", // Can be string name or signal number
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 11 transpiles without error", () => {
	const code = `// Kill 'yes' after it emits over 100 bytes of output
const result = Bun.spawnSync({
  cmd: ["yes"], // or ["bun", "exec", "yes"] on Windows
  maxBuffer: 100,
});
// process exits`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 12 transpiles without error", () => {
	const code = `const child = Bun.spawn(["bun", "child.ts"], {
  ipc(message) {
    /**
     * The message received from the sub process
     **/
  },
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 13 transpiles without error", () => {
	const code = `const childProc = Bun.spawn(["bun", "child.ts"], {
  ipc(message, childProc) {
    /**
     * The message received from the sub process
     **/
    childProc.send("Respond to child");
  },
});

childProc.send("I am your father"); // The parent can send messages to the child as well`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 14 transpiles without error", () => {
	const code = `process.send("Hello from child as string");
process.send({ message: "Hello from child as object" });

process.on("message", message => {
  // print message from parent
  console.log(message);
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 15 transpiles without error", () => {
	const code = `// send a string
process.send("Hello from child as string");

// send an object
process.send({ message: "Hello from child as object" });`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 16 transpiles without error", () => {
	const code = `if (typeof Bun !== "undefined") {
  const prefix = \`[bun \${process.versions.bun} 🐇]\`;
  const node = Bun.spawn({
    cmd: ["node", __filename],
    ipc({ message }) {
      console.log(message);
      node.send({ message: \`\${prefix} 👋 hey node\` });
      node.kill();
    },
    stdio: ["inherit", "inherit", "inherit"],
    serialization: "json",
  });

  node.send({ message: \`\${prefix} 👋 hey node\` });
} else {
  const prefix = \`[node \${process.version}]\`;
  process.on("message", ({ message }) => {
    console.log(message);
    process.send({ message: \`\${prefix} 👋 hey bun\` });
  });
}`;
	const transpiler = new Bun.Transpiler({ loader: "js" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 17 transpiles without error", () => {
	const code = `proc.terminal.write("echo hello\\n");

// Resize the terminal
proc.terminal.resize(120, 40);

// Set raw mode (disable line buffering and echo)
proc.terminal.setRawMode(true);

// Keep event loop alive while terminal is open
proc.terminal.ref();
proc.terminal.unref();

// Close the terminal
proc.terminal.close();`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 18 transpiles without error", () => {
	const code = `console.log(proc.stdout.toString());
// => "hello\\n"`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("spawn example 19 transpiles without error", () => {
	const code = `interface Bun {
  spawn(command: string[], options?: SpawnOptions.OptionsObject): Subprocess;
  spawnSync(command: string[], options?: SpawnOptions.OptionsObject): SyncSubprocess;

  spawn(options: { cmd: string[] } & SpawnOptions.OptionsObject): Subprocess;
  spawnSync(options: { cmd: string[] } & SpawnOptions.OptionsObject): SyncSubprocess;
}

namespace SpawnOptions {
  interface OptionsObject {
    cwd?: string;
    env?: Record<string, string | undefined>;
    stdio?: [Writable, Readable, Readable];
    stdin?: Writable;
    stdout?: Readable;
    stderr?: Readable;
    onExit?(
      subprocess: Subprocess,
      exitCode: number | null,
      signalCode: number | null,
      error?: ErrorLike,
    ): void | Promise<void>;
    ipc?(message: any, subprocess: Subprocess): void;
    serialization?: "json" | "advanced";
    windowsHide?: boolean;
    windowsVerbatimArguments?: boolean;
    argv0?: string;
    signal?: AbortSignal;
    timeout?: number;
    killSignal?: string | number;
    maxBuffer?: number;
    terminal?: TerminalOptions; // PTY (POSIX) / ConPTY (Windows) support
  }

  type Readable =
    | "pipe"
    | "inherit"
    | "ignore"
    | null // equivalent to "ignore"
    | undefined // to use default
    | BunFile
    | ArrayBufferView
    | number;

  type Writable =
    | "pipe"
    | "inherit"
    | "ignore"
    | null // equivalent to "ignore"
    | undefined // to use default
    | BunFile
    | ArrayBufferView
    | number
    | ReadableStream
    | Blob
    | Response
    | Request;
}

interface Subprocess extends AsyncDisposable {
  readonly stdin: FileSink | number | undefined | null;
  readonly stdout: ReadableStream<Uint8Array<ArrayBuffer>> | number | undefined | null;
  readonly stderr: ReadableStream<Uint8Array<ArrayBuffer>> | number | undefined | null;
  readonly readable: ReadableStream<Uint8Array<ArrayBuffer>> | number | undefined | null;
  readonly terminal: Terminal | undefined;
  readonly pid: number;
  readonly exited: Promise<number>;
  readonly exitCode: number | null;
  readonly signalCode: NodeJS.Signals | null;
  readonly killed: boolean;

  kill(exitCode?: number | NodeJS.Signals): void;
  ref(): void;
  unref(): void;

  send(message: any): void;
  disconnect(): void;
  resourceUsage(): ResourceUsage | undefined;
}

interface SyncSubprocess {
  stdout: Buffer | undefined;
  stderr: Buffer | undefined;
  exitCode: number;
  success: boolean;
  resourceUsage: ResourceUsage;
  signalCode?: string;
  exitedDueToTimeout?: true;
  pid: number;
}

interface TerminalOptions {
  cols?: number;
  rows?: number;
  name?: string;
  data?: (terminal: Terminal, data: Uint8Array<ArrayBuffer>) => void;
  /** Called when PTY stream closes (EOF or error). exitCode is PTY lifecycle status (0=EOF, 1=error), not subprocess exit code. */
  exit?: (terminal: Terminal, exitCode: number, signal: string | null) => void;
  drain?: (terminal: Terminal) => void;
}

interface Terminal extends AsyncDisposable {
  readonly stdin: number;
  readonly stdout: number;
  readonly closed: boolean;
  write(data: string | BufferSource): number;
  resize(cols: number, rows: number): void;
  setRawMode(enabled: boolean): void;
  ref(): void;
  unref(): void;
  close(): void;
}

interface ResourceUsage {
  contextSwitches: {
    voluntary: number;
    involuntary: number;
  };

  cpuTime: {
    user: number;
    system: number;
    total: number;
  };
  maxRSS: number;

  messages: {
    sent: number;
    received: number;
  };
  ops: {
    in: number;
    out: number;
  };
  shmSize: number;
  signalCount: number;
  swapCount: number;
}

type Signal =
  | "SIGABRT"
  | "SIGALRM"
  | "SIGBUS"
  | "SIGCHLD"
  | "SIGCONT"
  | "SIGFPE"
  | "SIGHUP"
  | "SIGILL"
  | "SIGINT"
  | "SIGIO"
  | "SIGIOT"
  | "SIGKILL"
  | "SIGPIPE"
  | "SIGPOLL"
  | "SIGPROF"
  | "SIGPWR"
  | "SIGQUIT"
  | "SIGSEGV"
  | "SIGSTKFLT"
  | "SIGSTOP"
  | "SIGSYS"
  | "SIGTERM"
  | "SIGTRAP"
  | "SIGTSTP"
  | "SIGTTIN"
  | "SIGTTOU"
  | "SIGUNUSED"
  | "SIGURG"
  | "SIGUSR1"
  | "SIGUSR2"
  | "SIGVTALRM"
  | "SIGWINCH"
  | "SIGXCPU"
  | "SIGXFSZ"
  | "SIGBREAK"
  | "SIGLOST"
  | "SIGINFO";`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
