import { expect, test } from "bun:test";

// Generated by api-docs from "Transpiler"

test("transpiler example 1 transpiles without error", () => {
	const code = `const transpiler = new Bun.Transpiler({
  loader: "tsx", // "js" | "jsx" | "ts" | "tsx"
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 2 transpiles without error", () => {
	const code = `transpiler.transformSync("<div>hi!</div>", "tsx");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 3 transpiles without error", () => {
	const code = `const transpiler = new Bun.Transpiler({ loader: "jsx" });
const result = await transpiler.transform("<div>hi!</div>");
console.log(result);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 4 transpiles without error", () => {
	const code = `await transpiler.transform("<div>hi!</div>", "tsx");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
