import { expect, test } from "bun:test";

// Generated by api-docs from bun-types "Transpiler"

test("transpiler example 1 transpiles without error", () => {
	const code = `const transpiler = new Bun.Transpiler({
  loader: 'tsx',
});

const code = \`
import * as whatever from "./whatever.ts"
export function Home(props: {title: string}){
  return <p>{props.title}</p>;
}\`;

const result = transpiler.transformSync(code);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 2 transpiles without error", () => {
	const code = `import { __require as require } from "bun:wrap";
import * as JSX from "react/jsx-dev-runtime";
var jsx = require(JSX).jsxDEV;

export default jsx(
  "div",
  {
    children: "hi!",
  },
  undefined,
  false,
  undefined,
  this,
);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 3 transpiles without error", () => {
	const code = `const result = await transpiler.transform("<div>hi!</div>");
console.log(result);`;
	const transpiler = new Bun.Transpiler({ loader: "js" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 4 transpiles without error", () => {
	const code = `const transpiler = new Bun.Transpiler({
  loader: "tsx",
});

const code = \`
import React from 'react';
import type {ReactNode} from 'react';
const val = require('./cjs.js')
import('./loader');

export const name = "hello";
\`;

const result = transpiler.scan(code);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("transpiler example 5 transpiles without error", () => {
	const code = `const transpiler = new Bun.Transpiler({
  loader: "tsx",
});

const code = \`
import React from 'react';
import type {ReactNode} from 'react';
const val = require('./cjs.js')
import('./loader');

export const name = "hello";
\`;

const result = transpiler.scanImports(code);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
