import { expect, test } from "bun:test";

// Generated by api-docs from "UDP"

test("udp example 1 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({});
console.log(socket.port); // assigned by the operating system`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 2 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({
  port: 41234, 
});

console.log(socket.port); // 41234`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 3 transpiles without error", () => {
	const code = `socket.send("Hello, world!", 41234, "127.0.0.1");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 4 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({});

// sends 'Hello' to 127.0.0.1:41234, and 'foo' to 1.1.1.1:53 in a single operation
socket.sendMany(["Hello", 41234, "127.0.0.1", "foo", 53, "1.1.1.1"]);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 5 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({
  connect: {
    port: 41234,
    hostname: "localhost",
  },
});

socket.sendMany(["foo", "bar", "baz"]);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 6 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({
  socket: {
    drain(socket) {
      // continue sending data
    },
  },
});`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 7 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({});

// Enable broadcasting to send packets to a broadcast address
socket.setBroadcast(true);

// Set the IP TTL (time to live) for outgoing packets
socket.setTTL(64);`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 8 transpiles without error", () => {
	const code = `const socket = await Bun.udpSocket({});

// Join a multicast group
socket.addMembership("224.0.0.1");

// Join with a specific interface
socket.addMembership("224.0.0.1", "192.168.1.100");

// Leave a multicast group
socket.dropMembership("224.0.0.1");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 9 transpiles without error", () => {
	const code = `// Set TTL for multicast packets (number of network hops)
socket.setMulticastTTL(2);

// Control whether multicast packets loop back to the local socket
socket.setMulticastLoopback(true);

// Specify which interface to use for outgoing multicast packets
socket.setMulticastInterface("192.168.1.100");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});

test("udp example 10 transpiles without error", () => {
	const code = `socket.addSourceSpecificMembership("10.0.0.1", "232.0.0.1");
socket.dropSourceSpecificMembership("10.0.0.1", "232.0.0.1");`;
	const transpiler = new Bun.Transpiler({ loader: "ts" });
	expect(() => transpiler.transformSync(code)).not.toThrow();
});
